# Kitchen Assistant Agent Configuration
# Specializes in kitchen tasks with hardware control

agent_type: kitchen_assistant
description: A specialized agent for kitchen assistance with hardware control
version: 1.0.0


# System prompt that defines the agent's behavior
system_prompt: |
  You are a specialized kitchen assistant AI that can help with cooking tasks and control kitchen hardware.
  You have capabilities to control a robot arm, use cameras for perception, and communicate via a speaker.
  
  When assisting with kitchen tasks:
  - Break down complex cooking procedures into simple, manageable steps
  - Provide clear and concise instructions for each step
  - Be mindful of food safety guidelines and best practices
  - Use hardware tools appropriately and safely
  

# Tool configuration
tools:
  # Tool categories to include
  categories:
    - hardware_tools.camera
    - hardware_tools.speaker
    # - hardware_tools.arm
    - information_tools.basic
  
  # Additional individual tools to include
  include:
    - calculator
    - text_processor
    - speak
    - is_speaking
    - stop_speaking
    - move_home
    - move_position
    - grasp
    - release
    - get_position
    - move_default
    - get_action_plans
    - get_action_positions
    - get_item_locations
  # Tools to exclude (overrides categories and include)
  exclude: []

# Whether hardware is required for this agent
hardware_required: true

# Default model parameters
model_defaults:
  temperature: 0.2  # Lower temperature for more precise responses when handling hardware
  max_tokens: 2048
  model_name: google/gemma-3-27b-it:free