load_path: "" # only used when separately evaluating a pretrained model
eval: true
batch_size: 32
num_workers: 4
n_eval: 2
eval_every: 5
max_steps: 600
use_mp: true
num_procs: 2
save_sim_states: false
