# Hardware Tools Configuration
# Defines tools for interacting with physical hardware

categories:
  # Camera tools for environment perception
  camera:
    description: Tools for environment perception
    tools:
      - name: capture_environment
        description: Capture an image from the environment camera
        hardware_required: true
        parameters: []
      
      - name: capture_wrist
        description: Capture an image from the wrist-mounted camera
        hardware_required: true
        parameters: []
      
      - name: capture_both
        description: Capture images from both environment and wrist cameras
        hardware_required: true
        parameters: []
  
  # Speaker tools for user communication
  speaker:
    description: Tools for user communication
    tools:
      - name: speak
        description: Convert text to speech
        hardware_required: true
        parameters:
          - name: text
            type: string
            description: Text to speak
      
      - name: is_speaking
        description: Check if the speaker is currently active
        hardware_required: true
        parameters: []
      
      - name: stop_speaking
        description: Stop any current speech or audio playback
        hardware_required: true
        parameters: []
  
  # Robotic arm tools for physical interaction
  arm:
    description: Robotic arm control tools for physical interaction
    tools:
      - name: move_home
        description: Move the arm to the home position
        hardware_required: true
        parameters: []
      
      - name: move_position
        description: Move the arm to a specific Cartesian position
        hardware_required: true
        parameters:
          - name: x
            type: float
            description: X-coordinate (mm)
          - name: y
            type: float
            description: Y-coordinate (mm)
          - name: z
            type: float
            description: Z-coordinate (mm)
          - name: roll
            type: float
            description: Roll angle (degrees)
            optional: true
            default: 0.0
          - name: pitch
            type: float
            description: Pitch angle (degrees)
            optional: true
            default: 0.0
          - name: yaw
            type: float
            description: Yaw angle (degrees)
            optional: true
            default: 0.0
      
      - name: grasp
        description: Close the gripper to grasp an object
        hardware_required: true
        parameters:
          - name: strength
            type: float
            description: Gripping strength (0.0-1.0)
            optional: true
            default: 0.5
      
      - name: release
        description: Open the gripper to release an object
        hardware_required: true
        parameters: []
      
      - name: get_position
        description: Get the current position of the robotic arm
        hardware_required: true
        parameters: []
      
      - name: move_default
        description: Move the arm to a default position suitable for kitchen tasks
        hardware_required: true
        parameters: [] 

# Tool prompts for LLM system prompts
tool_prompts:
  # Camera tools
  capture_environment:
    description: "Capture an image from the environment camera"
    parameters: []
    example: '{"tool_name": "capture_environment", "parameters": {}}'
  
  capture_wrist:
    description: "Capture an image from the wrist-mounted camera"
    parameters: []
    example: '{"tool_name": "capture_wrist", "parameters": {}}'
  
  capture_both:
    description: "Capture images from both environment and wrist cameras"
    parameters: []
    example: '{"tool_name": "capture_both", "parameters": {}}'
  
  # Speaker tools
  speak:
    description: "Convert text to speech"
    parameters:
      - name: text
        description: "Text to speak"
    example: '{"tool_name": "speak", "parameters": {"text": "Hello, how can I help you with your cooking today?"}}'
  
  is_speaking:
    description: "Check if the speaker is currently active"
    parameters: []
    example: '{"tool_name": "is_speaking", "parameters": {}}'
  
  stop_speaking:
    description: "Stop any current speech or audio playback"
    parameters: []
    example: '{"tool_name": "stop_speaking", "parameters": {}}'
  
  # Robotic arm tools
  move_home:
    description: "Move the arm to the home position"
    parameters: []
    example: '{"tool_name": "move_home", "parameters": {}}'
  
  move_position:
    description: "Move the arm to a specific Cartesian position"
    parameters:
      - name: x
        description: "X-coordinate (mm)"
      - name: y
        description: "Y-coordinate (mm)"
      - name: z
        description: "Z-coordinate (mm)"
      - name: roll
        description: "Roll angle (degrees)"
      - name: pitch
        description: "Pitch angle (degrees)"
      - name: yaw
        description: "Yaw angle (degrees)"
    example: '{"tool_name": "move_position", "parameters": {"x": 250, "y": 300, "z": 200, "roll": 0, "pitch": 45, "yaw": 0}}'
  
  grasp:
    description: "Close the gripper to grasp an object"
    parameters:
      - name: strength
        description: "Gripping strength (0.0-1.0)"
    example: '{"tool_name": "grasp", "parameters": {"strength": 0.7}}'
  
  release:
    description: "Open the gripper to release an object"
    parameters: []
    example: '{"tool_name": "release", "parameters": {}}'
  
  get_position:
    description: "Get the current position of the robotic arm"
    parameters: []
    example: '{"tool_name": "get_position", "parameters": {}}'
  
  move_default:
    description: "Move the arm to a default position suitable for kitchen tasks"
    parameters: []
    example: '{"tool_name": "move_default", "parameters": {}}' 